# This file contains the configuration for Credo and you are probably reading
# this after creating it with `mix credo.gen.config`.
#
# If you find anything wrong or unclear in this file, please report an
# issue on GitHub: https://github.com/rrrene/credo/issues
#
version: 2.1
orbs:
  elixir: membraneframework/elixir@1

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test
      - elixir/test
      - elixir/lint
